### ISSUE TITLE
Allow for different image alignment with [grid] shortcode

### ISSUE THREAD

**Issue by Jared-Williams** [maiprowp/mai-pro-engine#100]
We already chatted about this via slack. Just thought I'd drop this here in case we wanted to continue the discussion. 

For anyone else wondering, it was for the ability to align images to the left or right of the Title and Content. Even though it's a [grid] shortcode, there are times when we don't always need it displayed in a grid. The shortcode does everything else already...

_Not an issue, more of a feature request_

**Comment by JiveDig** [comment]
FWIW: This is already in the works.

**Comment by JiveDig** [comment]
Done in 1.1.2
