### ISSUE TITLE
Remove 'else' in site title rebuild

### ISSUE THREAD

**Issue by JiveDig** [maiprowp/mai-pro-engine#103]
As pointed out by Robin C, can just use the $inside that gets passed to the filter, if no logo is set.
```
	} else {
		// If no custom logo, wrap around the site name.
		$inside = sprintf( '<a href="%s" title="%s">%s</a>', trailingslashit( home_url() ), esc_attr( $site_title ), esc_html( $site_title ) );
	}
```

**Comment by craigsimps** [comment]
Does `$title` still need to be modified if no logo is set? Could you not simply do:

```
if ( ! ( function_exists( 'has_custom_logo' ) && has_custom_logo() ) ) {
	return $title;
}
```

**Comment by JiveDig** [comment]
@craigsimps Yes, this is what Robin pointed out. It's actually the `$inside` variable, but the point still applies... unless i'm missing what you are suggesting.

**Comment by JiveDig** [comment]
Ohhh, just looked at my code... yeah just bail early and returning the original stuff. Right on.

**Comment by JiveDig** [comment]
Fixed https://github.com/maiprowp/mai-pro-engine/commit/ecf11c94ba88c3e52cc762625cb679ac9283918b
