### ISSUE TITLE
Sections template content doesn't show up in search

### ISSUE THREAD

**Issue by JiveDig** [maiprowp/mai-pro-engine#88]
Obviously, since it's meta... but maybe we should allow it?

https://adambalee.com/search-wordpress-by-custom-fields-without-a-plugin/

**Comment by JiveDig** [comment]
New plan: On post_save, if Section page template, grab the post_meta/cmb/field data and dump it all into the post_content.

**Comment by dws122** [comment]
Add it to post_content ?

**Comment by JiveDig** [comment]
Yes, since WP is indexing the post_content column for search, that would make it easier than adding meta to the index. Right now Section template pages are not correctly searchable. It may add confusion later if they switch from Sectio template to something else like default template, but seems to be worth the tradeoff.

**Comment by dws122** [comment]
Robin and Brandi also reported that the content does not show up in Yoast's SEO tools.

**Comment by JiveDig** [comment]
Now adds to post_content via a CMB2 hook on post save.
