### ISSUE TITLE
Curly quotes not working in section template

### ISSUE THREAD

**Issue by skydogtech** [maiprowp/mai-pro-engine#92]
The straight quotes in section template content area are not being converted to curly quotes on the front end.

![no-curly-quotes](https://user-images.githubusercontent.com/6430858/29371656-f21dd8bc-8276-11e7-861d-b269d54fb7c2.png)

**Comment by skydogtech** [comment]
hmm, same is true in mai banner text, pulled from page/post excerpt (see attached)
![walks](https://user-images.githubusercontent.com/6430858/29412753-fcd41bac-8327-11e7-8c4f-3571dd1a9e9a.png)

**Comment by JiveDig** [comment]
Hmmm good find. That will help me narrow it down. They both use the section helper function on output, so this makes me think it's during the escape upon output.

**Comment by JiveDig** [comment]
I'm thinking this another issue related to https://github.com/maiprowp/mai-pro-engine/issues/95

**Comment by JiveDig** [comment]
Found this: https://codex.wordpress.org/Function_Reference/wptexturize

**Comment by skydogtech** [comment]
ooooh promising!!

**Comment by JiveDig** [comment]
Fixed https://github.com/maiprowp/mai-pro-engine/commit/ecf11c94ba88c3e52cc762625cb679ac9283918b

**Comment by skydogtech** [comment]
great!
